"""Add created_on and updated_on columns in Sources Table

Revision ID: 4c63afa980df
Revises: a5a185a2c72a
Create Date: 2025-05-23 00:43:40.528033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c63afa980df'
down_revision: Union[str, None] = 'a5a185a2c72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('sources', sa.Column('updated_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'updated_on')
    op.drop_column('sources', 'created_on')
    # ### end Alembic commands ###
