"""Create Sources Table

Revision ID: a5a185a2c72a
Revises: 
Create Date: 2025-05-22 01:24:43.384700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a185a2c72a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('title_selector', sa.String(), nullable=False),
    sa.Column('price_selector', sa.String(), nullable=False),
    sa.Column('rating_selector', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_sources_domain', 'sources', ['domain'], unique=False)
    op.create_index('idx_sources_name', 'sources', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sources_name', table_name='sources')
    op.drop_index('idx_sources_domain', table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
